/** Declaration file generated by dts-gen */
declare module 'hookrouter' {
    export function A(props: any): any;

    export function getBasepath(): any;

    export function getPath(): any;

    export function getQueryParams(): any;

    export function getTitle(): any;

    export function navigate(url: any, ...args: any[]): void;

    export function setBasepath(inBasepath: any): void;

    export function setLinkProps(props: any): any;

    export function setPath(inPath: any): void;

    export function setQueryParams(inObj: any): any;

    export function useControlledInterceptor(): any;

    export function useInterceptor(handlerFunction: any): any;

    export function useQueryParams(): any;

    export function useRedirect(fromURL: any, toURL: any, ...args: any[]): void;

    export function useRoutes(routeObj: any, ...args: any[]): any;

    export function useTitle(inString: any): any;

    export namespace A {
        const prototype: {
        };

    }

    export namespace getBasepath {
        const prototype: {
        };

    }

    export namespace getPath {
        const prototype: {
        };

    }

    export namespace getQueryParams {
        const prototype: {
        };

    }

    export namespace getTitle {
        const prototype: {
        };

    }

    export namespace navigate {
        const prototype: {
        };

    }

    export namespace setBasepath {
        const prototype: {
        };

    }

    export namespace setLinkProps {
        const prototype: {
        };

    }

    export namespace setPath {
        const prototype: {
        };

    }

    export namespace setQueryParams {
        const prototype: {
        };

    }

    export namespace useControlledInterceptor {
        const prototype: {
        };

    }

    export namespace useInterceptor {
        const prototype: {
        };

    }

    export namespace useQueryParams {
        const prototype: {
        };

    }

    export namespace useRedirect {
        const prototype: {
        };

    }

    export namespace useRoutes {
        const prototype: {
        };

    }

    export namespace useTitle {
        const prototype: {
        };

    }
}